apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://bookstore-prometheus-perf:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"