# Tricentis API Simulator Configuration
# Simulates LLM provider APIs for zero-cost performance testing

Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    System: Warning

# Simulation definitions will be loaded from this configuration
# The simulator intercepts HTTP requests and returns predefined responses
# based on URL patterns and request content

Simulator:
  Name: "BookStore LLM API Simulator"
  Version: "1.0.0"
  Description: "Simulates Claude, OpenAI, and Bedrock APIs for cost-free performance testing"

  # Enable detailed logging for debugging
  VerboseLogging: true

  # Track all API invocations
  EnableTracking: true

  # Response delays (milliseconds) to simulate real API latency
  DefaultDelay: 100

  # Simulation rules (simplified - full definitions will be added in Phase 2)
  Rules:
    - Name: "Claude Messages API"
      Pattern: "/v1/messages"
      Method: "POST"
      Response:
        StatusCode: 200
        ContentType: "application/json"
        Body: |
          {
            "id": "msg_01sim123",
            "type": "message",
            "role": "assistant",
            "content": [{
              "type": "text",
              "text": "This is a simulated book summary generated by the API Simulator. In a real scenario, this would be a thoughtful AI-generated summary of the book's themes, plot, and significance."
            }],
            "model": "claude-3-5-sonnet-20241022",
            "stop_reason": "end_turn",
            "usage": {
              "input_tokens": 45,
              "output_tokens": 67
            }
          }
      Delay: 150

    - Name: "OpenAI Chat Completions"
      Pattern: "/v1/chat/completions"
      Method: "POST"
      Response:
        StatusCode: 200
        ContentType: "application/json"
        Body: |
          {
            "id": "chatcmpl-sim123",
            "object": "chat.completion",
            "created": 1234567890,
            "model": "gpt-4o-mini",
            "choices": [{
              "index": 0,
              "message": {
                "role": "assistant",
                "content": "This is a simulated book summary from OpenAI. The simulator provides realistic responses without incurring actual API costs."
              },
              "finish_reason": "stop"
            }],
            "usage": {
              "prompt_tokens": 50,
              "completion_tokens": 70,
              "total_tokens": 120
            }
          }
      Delay: 180

    - Name: "Health Check"
      Pattern: "/health"
      Method: "GET"
      Response:
        StatusCode: 200
        ContentType: "application/json"
        Body: |
          {
            "status": "healthy",
            "simulator": "active",
            "mode": "zero-cost-testing"
          }
      Delay: 0

# Note: Comprehensive simulation definitions will be added in Phase 2
# This basic configuration allows Phase 1 infrastructure testing
